name: Deploy Pages Artifact

on:
  repository_dispatch:
    types: [ deploy-pages-from-artifact ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        with:
          artifact_id: ${{ github.event.client_payload.artifact_id }}
