name: Deploy Pages Artifact

on:
  repository_dispatch:
    types: [ deploy-pages-from-artifact ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Download source build artifact
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ github.event.client_payload.artifact_id }}
          run-id: ${{ github.event.client_payload.run_id }}
          path: extracted-site
          github-token: ${{ secrets.REPOSTITORY_PAYLOAD_TOKEN }}
          repository: "redwyre/FriendlyTimeline"
          skip-decompress: true

      - name: Upload Pages artifact
        uses: actions/upload-artifact@v7
        with:
          path: extracted-site
          name: github-pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
