name: Deploy Pages Artifact

on:
  repository_dispatch:
    types: [ deploy-pages-from-artifact ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download source build artifact
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ github.event.client_payload.artifact_id }}
          run-id: ${{ github.event.client_payload.run_id }}
          path: extracted-site
          github-token: ${{ secrets.REPOSTITORY_PAYLOAD_TOKEN }}
          repository: "redwyre/FriendlyTimeline"

      # - name: Delete github-pages artifact
      #   run: rm ./github-pages.zip
      #   working-directory: extracted-site

      - name: Extract content
        run: tar -xvf ./artifact.tar
        working-directory: extracted-site

      - name: Delete artifact
        run: rm ./artifact.tar
        working-directory: extracted-site

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: extracted-site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
